version: 2

updates:

  # GitHub Actions
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: ci
    groups:
      ci:
        patterns:
          - '*'

  # Rust
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: monthly
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: deps
    groups:
      rust:
        patterns:
          - '*'

  # Python
  - package-ecosystem: "uv"
    directory: "/python"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    commit-message:
      prefix: deps
    groups:
      python:
        patterns:
          - '*'

