from collections.abc import Iterator
from pathlib import Path

class MarcReader:
    def __init__(
        self,
        sources: str | list[str] | Path | list[Path],
        query: str,
        *,
        predicate: str | None = None,
        skip_invalid: bool = True,
    ) -> None: ...
    def names(self) -> list[str]: ...
    def width(self) -> int: ...
    def dtypes(self) -> list[str]: ...
    def __len__(self) -> int: ...
    def __next__(self) -> Iterator[list[str]]: ...
