[project]
name = "marc21-learn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Nico Wagner", email = "n.wagner@dnb.de" }]
requires-python = ">=3.14"
dependencies = [
    "numpy>=2.5.2",
]

[project.scripts]
marc21-learn = "marc21_learn:main"

[tool.maturin]
module-name = "marc21_learn._learn"
python-packages = ["marc21_learn"]
python-source = "src"

[tool.uv]
cache-keys = [
  { file = "pyproject.toml" },
  { file = "src/**/*.rs" },
  { file = "Cargo.toml" },
  { file = "Cargo.lock" },
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[dependency-groups]
dev = [
    "ruff>=0.16.5",
    "ruff-lsp>=0.0.62",
    "ty>=0.0.75",
]
