"""Polars I/O Plugin."""

from glob import glob
from pathlib import Path
from typing import TYPE_CHECKING

import polars as pl
from polars.io.plugins import register_io_source

from marc21_learn._runtime.io import MarcReader

if TYPE_CHECKING:
    from collections.abc import Iterator


def normalize_filepath(path: str | Path) -> list[Path]:
    if isinstance(path, str):
        path = str(Path(path).expanduser())
        return [Path(p) for p in glob(path)]  # noqa: PTH207
    return [Path(path).expanduser().absolute()]


def prepare_sources(
    sources: str | Path | list[str] | list[Path],
) -> list[Path]:
    if isinstance(sources, (str, Path)):
        paths = normalize_filepath(sources)
    else:
        paths: list[Path] = []
        for source in sources:
            paths.extend(normalize_filepath(source))

    return paths


def prepare_header(
    header: str | list[str] | None,
    reader: MarcReader,
) -> list[str]:
    if not header:
        header = reader.names()
    elif isinstance(header, str):
        header = list(map(str.strip, header.split(",")))

    if len(header) != reader.width():
        raise ValueError

    return header


def parse_schema(header: list[str], dtypes: list[str]) -> pl.Schema:
    mapping = {}

    for key, dtype in zip(header, dtypes, strict=True):
        match dtype:
            case "uint32":
                mapping[key] = pl.UInt32
            case "char" | "string" | _:
                mapping[key] = pl.String

    return pl.Schema(mapping)


def scan_marc21(
    sources: str | Path | list[str] | list[Path],
    query: str,
    *,
    header: str | list[str] | None = None,
    predicate: str | None = None,
    skip_invalid: bool = True,
) -> pl.LazyFrame:
    """
    Read and project MARC21 files into a LazyFrame.

    Parameters
    ----------
    sources
        Path(s) to MARC21 files. Files with `.gz` suffix (compressed in
        Gzip format) are automatically decompressed.
    query
        A query that defines the projection to be performed.
    header
        Specify the column names either as list of strings or as a
        comma separated list. If no header is specified the column names
        are autogenerated in the following format: `column_x`, with
        `x` being an enumeration over every column of the projection,
        starting at 1.
    where
        A filter expression used to filter records in advance. This
        prevents unnecessary memory allocations and thereby improves
        significantly the performance of the query execution.

    Examples
    --------
    >>> from marc21_learn.io import scan_marc21
    >>> df = scan_marc21("../tests/data/ada.mrc.gz", "001 AS `cn`").collect()
    >>> df
    shape: (1, 1)
    ┌───────────┐
    │ cn        │
    │ ---       │
    │ str       │
    ╞═══════════╡
    │ 119232022 │
    └───────────┘
    """
    reader = MarcReader(
        prepare_sources(sources),
        query,
        skip_invalid=skip_invalid,
        predicate=predicate,
    )

    header = prepare_header(header, reader)
    schema = parse_schema(header, reader.dtypes())

    def source_generator(
        with_columns: list[str] | None,
        predicate: pl.Expr | None,
        n_rows: int | None,
        batch_size: int | None,
    ) -> Iterator[pl.DataFrame]:

        if batch_size is None:
            batch_size = 100

        while n_rows is None or n_rows > 0:
            if n_rows is not None:
                batch_size = min(batch_size, n_rows)

            rows = []

            for _ in range(batch_size):
                try:
                    row = next(reader)
                    rows.append(row)
                except StopIteration:
                    n_rows = 0
                    break

            df = pl.from_records(rows, schema=schema, orient="row")

            if n_rows is not None:
                n_rows -= df.height

            if with_columns is not None:
                df = df.select(with_columns)

            if predicate is not None:
                df = df.filter(predicate)

            yield df

    return register_io_source(io_source=source_generator, schema=schema)


def read_marc21(
    sources: str | Path | list[str] | list[Path],
    query: str,
    *,
    header: str | list[str] | None = None,
    predicate: str | None = None,
) -> pl.DataFrame:
    """
    Read and project MARC21 files into a DataFrame.

    Parameters
    ----------
    sources
        Path(s) to MARC21 files. Files with `.gz` suffix (compressed in
        Gzip format) are automatically decompressed.
    query
        A query that defines the projection to be performed.
    header
        Specify the column names either as list of strings or as a
        comma separated list. If no header is specified the column names
        are autogenerated in the following format: `column_x`, with
        `x` being an enumeration over every column of the projection,
        starting at 1.
    where
        A filter expression used to filter records in advance. This
        prevents unnecessary memory allocations and thereby improves
        significantly the performance of the query execution.

    """
    return scan_marc21(
        sources,
        query,
        header=header,
        predicate=predicate,
    ).collect()
