[package]
name = "marc21-cli"
version = "0.6.0"
authors.workspace = true
repository.workspace = true
description = "A command-line tool for processing MARC-21 records."
categories = ["command-line-utilities"]
keywords = ["marc21", "cli", "code4lib"]
license.workspace = true
rust-version.workspace = true
edition.workspace = true

[[bin]]
name = "marc21"
path = "src/main.rs"

[[test]]
path = "tests/e2e/lib.rs"
name = "e2e"

[[test]]
path = "tests/book/lib.rs"
name = "book"

[dependencies]
bstr = { workspace = true, features = ["std"], default-features = false }
clap_complete = { workspace = true, optional = true }
clap_mangen = { workspace = true, optional = true }
clap = { workspace = true, features = ["derive", "env", "wrap_help"] }
csv = { workspace = true }
dvrf = { workspace = true }
flate2 = { workspace = true }
indicatif = { workspace = true }
marc21 = { workspace = true, features = ["serde"] }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true, features = ["derive"] }
sha2 = { workspace = true }
sophia = { workspace = true }
toml = { workspace = true, features = ["preserve_order"] }
unicode-normalization = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
assert_cmd = { workspace = true }
assert_fs = { workspace = true }
predicates = { workspace = true }
trycmd = { workspace = true }

[features]
default = ["performant"]

# Commands and functions that are only needed during the build process
# or packaging are activated with the `build` feature. This includes,
# for example, the commands for generating man pages (`build-man`) and
# shell completions (`build-completion`).
build = ["dep:clap_mangen", "dep:clap_complete"]

# This feature activates optimizations aimed at improving performance.
# This includes, for example, the activation of SIMD or a more
# aggressive inline strategy. Since the main goal of the project is high
# performance, the feature is enabled by default.
performant = ["marc21/performant"]

# New features that are still in the testing phase can be activated
# using the `unstable` feature. Keep in mind that these functions may
# change at any time.
unstable = ["marc21/unstable"]

# This features enables debug output of the marc21 crate.
# debug = ["marc21/debug"]
