from collections.abc import Iterator
from glob import glob
from pathlib import Path

import polars as pl
from polars.io.plugins import register_io_source

from polars_marc21._core import LazyReader


class HeaderLengthError(ValueError):
    """An exception raised when the header length is invalid."""


def normalize_filepath(path: str | Path) -> list[Path]:
    if isinstance(path, str):
        path = str(Path(path).expanduser())
        return [Path(p) for p in glob(path)]  # noqa: PTH207
    return [Path(path).expanduser().absolute()]


def prepare_sources(
    sources: str | Path | list[str] | list[Path],
) -> list[Path]:
    if isinstance(sources, (str, Path)):
        paths = normalize_filepath(sources)
    else:
        paths: list[Path] = []
        for source in sources:
            paths.extend(normalize_filepath(source))

    return paths


def prepare_header(
    header: str | list[str] | None,
    width: int,
) -> list[str]:
    if not header:
        header = [f"column_{i + 1}" for i in range(width)]
    elif isinstance(header, str):
        header = list(map(str.strip, header.split(",")))

    if len(header) != width:
        raise HeaderLengthError

    return header


def scan_marc21(
    sources: str | Path | list[str] | list[Path],
    query: str,
    *,
    header: str | list[str] | None = None,
    where: str | None = None,
) -> pl.LazyFrame:
    """
    Read and project MARC21 files into a LazyFrame.

    Parameters
    ----------
    sources
        Path(s) to MARC21 files. Files with `.gz` suffix (compressed in
        Gzip format) are automatically decompressed.
    query
        A query that defines the projection to be performed.
    header
        Specify the column names either as list of strings or as a
        comma separated list. If no header is specified the column names
        are autogenerated in the following format: `column_x`, with
        `x` being an enumeration over every column of the projection,
        starting at 1.
    where
        A filter expression used to filter records in advance. This
        prevents unnecessary memory allocations and thereby improves
        significantly the performance of the query execution.

    """
    sources = prepare_sources(sources)
    reader = LazyReader(sources, query, predicate=where)

    header = prepare_header(header, reader.width())
    schema = pl.Schema(dict.fromkeys(header, pl.String))

    def source_generator(
        with_columns: list[str] | None,
        predicate: pl.Expr | None,
        n_rows: int | None,
        batch_size: int | None,
    ) -> Iterator[pl.DataFrame]:

        if batch_size is None:
            batch_size = 100

        while n_rows is None or n_rows > 0:
            if n_rows is not None:
                batch_size = min(batch_size, n_rows)

            rows = []

            for _ in range(batch_size):
                try:
                    row = next(reader)
                    rows.append(row)
                except StopIteration:
                    n_rows = 0
                    break

            df = pl.from_records(rows, schema=schema, orient="row")

            if n_rows is not None:
                n_rows -= df.height

            if with_columns is not None:
                df = df.select(with_columns)

            if predicate is not None:
                df = df.filter(predicate)

            yield df

    return register_io_source(io_source=source_generator, schema=schema)


def read_marc21(
    sources: str | Path | list[str] | list[Path],
    query: str,
    *,
    header: str | list[str] | None = None,
    where: str | None = None,
) -> pl.DataFrame:
    """
    Read and project MARC21 files into a DataFrame.

    Parameters
    ----------
    sources
        Path(s) to MARC21 files. Files with `.gz` suffix (compressed in
        Gzip format) are automatically decompressed.
    query
        A query that defines the projection to be performed.
    header
        Specify the column names either as list of strings or as a
        comma separated list. If no header is specified the column names
        are autogenerated in the following format: `column_x`, with
        `x` being an enumeration over every column of the projection,
        starting at 1.
    where
        A filter expression used to filter records in advance. This
        prevents unnecessary memory allocations and thereby improves
        significantly the performance of the query execution.

    """
    return scan_marc21(
        sources, query, header=header, where=where,
    ).collect()
