use winnow::combinator::preceded;
use winnow::prelude::*;

use crate::matcher::MatchOptions;
use crate::matcher::leader::LeaderField;
use crate::matcher::leader::parse::parse_leader_field;
use crate::query::DataType;
use crate::{ByteRecord, Value};

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct LeaderExpr(LeaderField);

impl LeaderExpr {
    /// Returns the data types of all columns generated by this
    /// expression.
    pub(crate) fn dtypes(&self) -> Vec<DataType> {
        match self.0 {
            LeaderField::BaseAddr => vec![DataType::UInt32],
            LeaderField::Encoding => vec![DataType::Char],
            LeaderField::Length => vec![DataType::UInt32],
            LeaderField::Status => vec![DataType::Char],
            LeaderField::Type => vec![DataType::Char],
        }
    }

    /// Performs the projection on the given record and return a list of
    /// columns.
    pub(crate) fn project<'a>(
        &self,
        record: &ByteRecord<'a>,
        _options: &MatchOptions,
    ) -> Vec<Vec<Value<'a>>> {
        use LeaderField::*;

        let leader = record.leader();

        let value = match self.0 {
            BaseAddr => leader.base_addr().to_string(),
            Encoding => char::from(leader.encoding()).to_string(),
            Length => leader.length().to_string(),
            Status => char::from(leader.status()).to_string(),
            Type => char::from(leader.r#type()).to_string(),
        };

        vec![vec![value.into()]]
    }
}

pub(crate) fn parse_leader_expr(
    i: &mut &[u8],
) -> ModalResult<LeaderExpr> {
    preceded("ldr.", parse_leader_field)
        .map(LeaderExpr)
        .parse_next(i)
}
