[package]
name = "polars-marc21"
version = "0.3.0"
description = "Rust bindings for polars-marc21"
documentation.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true


[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
bstr = { workspace = true }
marc21 = { workspace = true }
pyo3 = { workspace = true, features = ["extension-module", "abi3-py39"] }
