use winnow::combinator::{opt, seq};
use winnow::prelude::*;

use crate::matcher::shared::parse_range;
use crate::matcher::tag::parse::parse_tag_matcher;
use crate::matcher::{MatchOptions, TagMatcher};
use crate::query::EMPTY_BYTE_STRING;
use crate::{ByteRecord, ControlField, DataType, Field, Value};

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct ControlFieldExpr {
    pub(crate) tag_matcher: TagMatcher,
    pub(crate) range: Option<(Option<usize>, Option<usize>)>,
}

impl ControlFieldExpr {
    /// Returns the data types of all columns generated by this
    /// expression.
    #[inline]
    pub(crate) fn dtypes(&self) -> Vec<DataType> {
        vec![DataType::String]
    }

    /// Performs the projection on the given record and return a list of
    /// columns.
    pub(crate) fn project<'a>(
        &self,
        record: &ByteRecord<'a>,
        _options: &MatchOptions,
    ) -> Vec<Vec<Value<'a>>> {
        let mut iter = record.fields();
        let mut rows = vec![];

        while let Some(Field::Control(ControlField { tag, value })) =
            iter.next()
        {
            if !self.tag_matcher.is_match(tag) {
                continue;
            }

            let value: &[u8] = if let Some(range) = self.range {
                match range {
                    (Some(start), Some(end)) => {
                        value.get(start..end).unwrap_or_default()
                    }
                    (Some(start), None) => value
                        .get(start..value.len())
                        .unwrap_or_default(),
                    (None, Some(end)) => {
                        value.get(0..end).unwrap_or_default()
                    }
                    _ => unreachable!(),
                }
            } else {
                value
            };

            rows.push(vec![value.into()]);
        }

        if rows.is_empty() {
            // If no matching control field is found, the result will be
            // a column with a single row containing an empty value.
            // This is important so that the Cartesian product can be
            // generated correctly in the overall query.
            rows.push(vec![Value::from(&EMPTY_BYTE_STRING)]);
        }

        rows
    }
}

pub(crate) fn parse_control_field_expr(
    i: &mut &[u8],
) -> ModalResult<ControlFieldExpr> {
    seq! { ControlFieldExpr {
        tag_matcher: parse_tag_matcher,
        range: opt(parse_range),
    }}
    .parse_next(i)
}
