use bstr::ByteVec;
use winnow::ascii::multispace1;
use winnow::combinator::{opt, preceded, seq, terminated};
use winnow::prelude::*;

use crate::matcher::TagMatcher;
use crate::matcher::shared::{
    parse_identifier, parse_range, parse_string, ws1,
};
use crate::matcher::tag::parse::parse_tag_matcher;
use crate::query::EMPTY_BYTE_STRING;
use crate::{
    ByteRecord, ControlField, DataType, Field, QueryOptions, Value,
};

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct ControlFieldExpr {
    pub(crate) tag_matcher: TagMatcher,
    pub(crate) range: Option<(Option<usize>, Option<usize>)>,
    pub(crate) prefix: Option<String>,
    pub(crate) suffix: Option<String>,
    pub(crate) name: Option<String>,
}

impl ControlFieldExpr {
    /// Returns the data types of all columns generated by this
    /// expression.
    #[inline]
    pub(crate) fn dtypes(&self) -> Vec<DataType> {
        vec![DataType::String]
    }

    #[inline]
    pub(crate) fn names(&self) -> Vec<Option<&String>> {
        vec![self.name.as_ref()]
    }

    /// Performs the projection on the given record and return a list of
    /// columns.
    pub(crate) fn project<'a>(
        &self,
        record: &ByteRecord<'a>,
        _options: &QueryOptions,
    ) -> Vec<Vec<Value<'a>>> {
        let mut iter = record.fields();
        let mut rows = vec![];

        while let Some(Field::Control(ControlField { tag, value })) =
            iter.next()
        {
            if !self.tag_matcher.is_match(tag) {
                continue;
            }

            let value: &[u8] = if let Some(range) = self.range {
                match range {
                    (Some(start), Some(end)) => {
                        value.get(start..end).unwrap_or_default()
                    }
                    (Some(start), None) => value
                        .get(start..value.len())
                        .unwrap_or_default(),
                    (None, Some(end)) => {
                        value.get(0..end).unwrap_or_default()
                    }
                    _ => unreachable!(),
                }
            } else {
                value
            };

            if self.prefix.is_some() || self.suffix.is_some() {
                let mut value = Vec::from(value);

                if let Some(ref bytes) = self.prefix {
                    value.insert_str(0, bytes);
                }

                if let Some(ref bytes) = self.suffix {
                    value.push_str(bytes);
                }

                rows.push(vec![value.into()]);
            } else {
                rows.push(vec![value.into()]);
            }
        }

        if rows.is_empty() {
            // If no matching control field is found, the result will be
            // a column with a single row containing an empty value.
            // This is important so that the Cartesian product can be
            // generated correctly in the overall query.
            rows.push(vec![Value::from(&EMPTY_BYTE_STRING)]);
        }

        rows
    }
}

pub(crate) fn parse_control_field_expr(
    i: &mut &[u8],
) -> ModalResult<ControlFieldExpr> {
    seq! { ControlFieldExpr {
        prefix: opt(terminated(parse_string, multispace1)),
        tag_matcher: parse_tag_matcher,
        range: opt(parse_range),
        suffix: opt(preceded(multispace1, parse_string)),
        name: opt(preceded(ws1("AS"), parse_identifier)),
    }}
    .parse_next(i)
}
