use winnow::combinator::{opt, preceded, seq};
use winnow::prelude::*;

use crate::matcher::leader::LeaderField;
use crate::matcher::leader::parse::parse_leader_field;
use crate::matcher::shared::{parse_identifier, ws1};
use crate::query::DataType;
use crate::{ByteRecord, QueryOptions, Value};

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct LeaderExpr {
    field: LeaderField,
    name: Option<String>,
}

impl LeaderExpr {
    /// Returns the data types of all columns generated by this
    /// expression.
    pub(crate) fn dtypes(&self) -> Vec<DataType> {
        match self.field {
            LeaderField::BaseAddr => vec![DataType::UInt32],
            LeaderField::Encoding => vec![DataType::Char],
            LeaderField::Length => vec![DataType::UInt32],
            LeaderField::Status => vec![DataType::Char],
            LeaderField::Type => vec![DataType::Char],
        }
    }

    #[inline]
    pub(crate) fn names(&self) -> Vec<Option<&String>> {
        vec![self.name.as_ref()]
    }

    /// Performs the projection on the given record and return a list of
    /// columns.
    pub(crate) fn project<'a>(
        &self,
        record: &ByteRecord<'a>,
        _options: &QueryOptions,
    ) -> Vec<Vec<Value<'a>>> {
        use LeaderField::*;

        let leader = record.leader();

        let value = match self.field {
            BaseAddr => leader.base_addr().to_string(),
            Encoding => char::from(leader.encoding()).to_string(),
            Length => leader.length().to_string(),
            Status => char::from(leader.status()).to_string(),
            Type => char::from(leader.r#type()).to_string(),
        };

        vec![vec![value.into()]]
    }
}

pub(crate) fn parse_leader_expr(
    i: &mut &[u8],
) -> ModalResult<LeaderExpr> {
    seq! { LeaderExpr {
        _: "ldr.",
        field: parse_leader_field,
        name: opt(preceded(ws1("AS"), parse_identifier)),
    }}
    .parse_next(i)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_leader_expr() {
        use LeaderField::*;

        macro_rules! parse_success {
            ($i:expr, $field:expr) => {
                assert_eq!(
                    parse_leader_expr.parse($i.as_bytes()).unwrap(),
                    LeaderExpr {
                        field: $field,
                        name: None,
                    }
                );
            };

            ($i:expr, $field:expr, $name:expr) => {
                assert_eq!(
                    parse_leader_expr.parse($i.as_bytes()).unwrap(),
                    LeaderExpr {
                        field: $field,
                        name: Some($name.into()),
                    }
                );
            };
        }

        parse_success!("ldr.base_addr AS addr", BaseAddr, "addr");
        parse_success!("ldr.encoding AS enc", Encoding, "enc");
        parse_success!("ldr.length AS len", Length, "len");
        parse_success!("ldr.status AS status", Status, "status");
        parse_success!("ldr.type AS type", Type, "type");

        parse_success!("ldr.base_addr", BaseAddr);
        parse_success!("ldr.encoding", Encoding);
        parse_success!("ldr.length", Length);
        parse_success!("ldr.status", Status);
        parse_success!("ldr.type", Type);
    }
}
