use winnow::combinator::{opt, preceded, seq};
use winnow::prelude::*;

use crate::matcher::MatchOptions;
use crate::matcher::shared::{parse_identifier, parse_string, ws1};
use crate::{ByteRecord, DataType, Value};

#[derive(Debug, Clone, PartialEq)]
pub(crate) struct LiteralExpr {
    value: String,
    name: Option<String>,
}

impl LiteralExpr {
    /// Returns the data types of all columns generated by this
    /// expression.
    #[inline(always)]
    pub(crate) fn dtypes(&self) -> Vec<DataType> {
        vec![DataType::String]
    }

    #[inline]
    pub(crate) fn names(&self) -> Vec<Option<&String>> {
        vec![self.name.as_ref()]
    }

    /// Performs the projection on the given record and return a list of
    /// columns.
    pub(crate) fn project<'a>(
        &self,
        _record: &ByteRecord<'a>,
        _options: &MatchOptions,
    ) -> Vec<Vec<Value<'a>>> {
        vec![vec![Value::from(self.value.clone())]]
    }
}

pub(crate) fn parse_literal_expr(
    i: &mut &[u8],
) -> ModalResult<LiteralExpr> {
    seq! { LiteralExpr {
        value: parse_string,
        name: opt(preceded(ws1("AS"), parse_identifier)),
    }}
    .parse_next(i)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_literal_expr() {
        macro_rules! parse_success {
            ($i:expr, $value:expr) => {
                assert_eq!(
                    parse_literal_expr.parse($i.as_bytes()).unwrap(),
                    LiteralExpr {
                        value: $value.to_string(),
                        name: None,
                    }
                );
            };

            ($i:expr, $value:expr, $name:expr) => {
                assert_eq!(
                    parse_literal_expr.parse($i.as_bytes()).unwrap(),
                    LiteralExpr {
                        value: $value.to_string(),
                        name: Some($name.into()),
                    }
                );
            };
        }

        parse_success!("'foo' AS bar", "foo", "bar");
        parse_success!("'' AS bar", "", "bar");
        parse_success!("'foo'", "foo");
    }
}
