name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUSTDOCFLAGS: "-Dwarnings"
  RUSTUP_MAX_RETRIES: 10
  RUST_BACKTRACE: 1

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: |
          cargo check --workspace

  deny:
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
        with:
          command: check bans licenses sources
          command-arguments: -c .config/deny.toml
          arguments: --workspace --all-features
          rust-version: stable

  ci:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - check
      - deny
    steps:
      - name: check for cancelled jobs
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: exit 1
      - name: check for failed jobs
        if: ${{ contains(needs.*.result, 'failure') }}
        run: exit 1
      - name: finish
        run: exit 0
