name: "Publish to PyPI"

on:
  push:
    tags:
      - 'py-*'

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      version: ${{ env.VERSION }}
      tag: ${{ env.TAG }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Get release version from Git tag
        env:
          TAG: ${{ github.ref_name }}
        run: |
          tag="${TAG}"
          version=${tag#py-}
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "TAG=$tag" >> $GITHUB_ENV
      - name: Create GitHub release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$TAG" --verify-tag --draft --generate-notes --title "polars-marc21 v$VERSION"

  test:
    runs-on: ${{ matrix.target.os }}
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu-latest, python-version: "3.11" }
          - { os: ubuntu-latest, python-version: "3.12" }
          - { os: ubuntu-latest, python-version: "3.13" }
          - { os: ubuntu-latest, python-version: "3.14" }
          - { os: ubuntu-latest, python-version: "3.15" }
          - { os: windows-latest, python-version: "3.15" }
          - { os: macos-latest, python-version: "3.15" }
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
            python-version: ${{ matrix.target.python-version }}
      - run: cd python && uv sync --locked --all-extras --dev
      - run: cd python && uv run pytest tests

  release:
    runs-on: ubuntu-latest
    needs: [prepare, test]
    environment:
      name: pypi
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      - name: Install Python 3.13
        run: |
          uv python install 3.13
      - name: Build Python package
        run: |
          cd python && uv build
      - name: Smoke Tests
        run: |
          cd python
          uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py
          uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      - name: Upload assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ needs.prepare.outputs.version }}
          TAG: ${{ needs.prepare.outputs.tag }}
        shell: bash
        run: |
          cd python
          gh release upload "${TAG}" dist/*.tar.gz
          gh release upload "${TAG}" dist/*.whl
      - name: Publish to PyPI
        run: |
          cd python && uv publish
    
