name: rust

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '00 02 * * *'

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.target.os }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - { os: ubuntu-latest, toolchain: stable, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: stable, triple: x86_64-unknown-linux-musl }
          - { os: ubuntu-latest, toolchain: beta, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: nightly, triple: x86_64-unknown-linux-gnu }
          - { os: ubuntu-latest, toolchain: "1.93", triple: x86_64-unknown-linux-gnu }
          - { os: windows-latest, toolchain: stable, triple: x86_64-pc-windows-msvc }
          - { os: windows-latest, toolchain: stable, triple: i686-pc-windows-msvc }
          - { os: macos-latest, toolchain: stable, triple: x86_64-apple-darwin }
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: ${{ matrix.target.toolchain }}
          targets: ${{ matrix.target.triple }}

      - name: Instal nextest
        uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
        with:
          tool: nextest
          
      - name: Run tests
        if: ${{ matrix.target.toolchain != 'nightly' }}
        run: |
          cargo nextest run --target ${{ matrix.target.triple }} --workspace -F performant,serde,build --no-fail-fast
          cargo test --target ${{ matrix.target.triple }} --doc --workspace -F performant,serde,build --no-fail-fast

      - name: Run tests (nightly)
        if: ${{ matrix.target.toolchain == 'nightly' }}
        run: |
          cargo nextest run --target ${{ matrix.target.triple }} --workspace --all-features --no-fail-fast
          cargo test --target ${{ matrix.target.triple }} --doc --workspace --all-features --no-fail-fast

  fuzz:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    timeout-minutes: 900
    strategy:
      matrix:
        item:
          - { target: record-matcher, max-total-time: 180 }
          - { target: byte-record, max-total-time: 180 }
          - { target: query, max-total-time: 180 }
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly

      - name: Install cargo-fuzz
        uses: dtolnay/install@d0dc46e85ffd2c174b5ac0489e17f95dae84fa5a # cargo-fuzz
      - run: |
          cargo fuzz run --jobs 2 ${{ matrix.item.target }} -- -max_total_time=${{ matrix.item.max-total-time }}

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          components: clippy

      - name: Run clippy
        run: |
          cargo clippy --workspace --all-features -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Run rustfmt
        run: |
          cargo fmt --all --check

  features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          
      - name: Install cargo-hack
        uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
        with:
          tool: cargo-hack
          
      - name: Check Powerset
        run: |
          cargo hack check --workspace --features performant,nightly --no-dev-deps --ignore-unknown-features

      - name: Test Powerset
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          cargo hack check --workspace --features performant,nightly --ignore-unknown-features

  miri:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
          components: miri
          
      - name: Install nextest
        uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
        with:
          tool: nextest

      - name: Run miri
        run: |
          cargo miri nextest run --workspace --all-features --lib

  careful:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly

      - name: Install nextest
        uses: taiki-e/install-action@ba47c86ac325773530516bb756137ac718732518 # v2.86.5
        with:
          tool: nextest

      - name: Install careful
        run: |
          cargo install cargo-careful

      - name: Run careful
        run: |
          cargo careful test --workspace --all-features --doc
          cargo careful nextest run --workspace

  udeps:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # master
        with:
          toolchain: nightly
      - name: Install udeps
        run: cargo install --locked cargo-udeps

      - name: Run udeps
        run: cargo udeps --workspace

  completions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Check completions
        run: |
          scripts/check-completions.sh

  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: crate-ci/typos@8a48f81b6c64dcfea44b3633223084c4be58ac5f # v1.49.0
        with:
          config: .typos.toml

  zizmor:
    runs-on: ubuntu-latest
    permissions:
      security-events: write # Required for upload-sarif
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          
      - name: Run zizmor
        uses: zizmorcore/zizmor-action@6599ee8b7a49aef6a770f63d261d214911a7ce02 # v0.6.0

  dco:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Check DCO
        run: |
          scripts/check-dco.sh

  deny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Run cargo-deny
        uses: EmbarkStudios/cargo-deny-action@3c6349835b2b7b196a839186cb8b78e02f7b5f25 # v2.1.1
        with:
          arguments: --config .deny.toml --workspace --all-features
          rust-version: stable

  conclusion:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs:
      - careful
      - clippy
      - completions
      - deny
      - dco
      - features
      - fuzz
      - miri
      - rustfmt
      - test
      - typos
      - udeps
      - zizmor
    steps:
      - name: Check for cancelled jobs
        if: ${{ contains(needs.*.result, 'cancelled') }}
        run: |
          exit 1

      - name: Check for failed jobs
        if: ${{ contains(needs.*.result, 'failure') }}
        run: |
          exit 1

      - name: Finish job
        run: |
          exit 0
